### ISSUE TITLE
How to add the files to Zigbee2Mqtt?

### ISSUE THREAD

**Issue by DeckardCain2014** [ExcelluxZ2MZHA/Excellux-ZigBee2mqtt#3]
How to add the files to Zigbee2Mqtt? Saving it in the zigbee2mqtt folder doesn't work, and saving it via the UI is not possible (as it is no complete class file)

**Comment by ExcelluxZ2MZHA** [comment]
Hi，please show a screenshot of the error page and we will tell you how to process it，tks



发自我的iPhone


------------------ Original ------------------
From: DeckardCain2014 ***@***.***&gt;
Date: Tue,Nov 5,2024 6:53 PM
To: ExcelluxZ2MZHA/Excellux-ZigBee2mqtt ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [ExcelluxZ2MZHA/Excellux-ZigBee2mqtt] How to add the files toZigbee2Mqtt? (Issue #3)





 
How to add the files to Zigbee2Mqtt? Saving it in the zigbee2mqtt folder doesn't work, and saving it via the UI is not possible (as it is no complete class file)

**Comment by DeckardCain2014** [comment]
Hi, I already closed the issue, as it was my fault to not adopt the device before adding the code file. Thanks anyway!
